services:
  server:
    build: .
    ports:
      - '1337:8000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

