version: '3.8'

services:

  app:
    build: .
    ports:
      - '1337:1337'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

