services:
  web_secret_agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1004:1337'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl --fail http://127.0.0.1/alive || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
