apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflected-note
  labels:
    category: web_client
    challenge: reflected-note
spec:
  replicas: 2
  selector:
    matchLabels:
      category: web_client
      challenge: reflected-note
  template:
    metadata:
      labels:
        category: web_client
        challenge: reflected-note
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: web
        image: gcr.io/glowing-reserve-336013/reflected-note
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 30