apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookies
  labels:
    category: web_client
    challenge: cookies
spec:
  replicas: 1
  selector:
    matchLabels:
      category: web_client
      challenge: cookies
  template:
    metadata:
      labels:
        category: web_client
        challenge: cookies
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: web
        image: gcr.io/glowing-reserve-336013/cookies
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 30