version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

