deployment:
  additionalContainers: {}
  dockerRepository: gcr.io/mentoring-program-371116
  egress: deny
  healthCheck:
    initialDelaySeconds: 10
    periodSeconds: 100
  limits:
    cpu: 100m
    memory: 100Mi
  other:
    podAnnotations: {}
  replicasNumber: 1
  requests:
    cpu: 10m
    memory: 30Mi
