apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    category: scripting
    challenge: login
spec:
  replicas: 1
  selector:
    matchLabels:
      category: scripting
      challenge: login
  template:
    metadata:
      labels:
        category: scripting
        challenge: login
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/login
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: tcp
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 3
          periodSeconds: 30