apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    category: scripting
    challenge: login
spec:
  type: NodePort
  selector:
    category: scripting
    challenge: login
  ports:
    - port: 1337
      name: tcp
      targetPort: 1337
      nodePort: 30400